development:
  adapter: mysql2
  encoding: utf8mb4
  database: simple_chat_development
  host: localhost
  username: root
  password: password

test:
  adapter: mysql2
  encoding: utf8mb4
  database: simple_chat_test
  host: localhost
  username: root
  password: password

production:
  adapter: mysql2
  encoding: utf8mb4
  database: simple_chat_production
  host: localhost
  username: root
  password: password